import { describe, it, expect } from 'vitest';
import { parseJSON } from '../../src/plugin/src/parser/jsonParser';
import { validateImportData } from '../../src/plugin/src/utils/validation';

const validCapture = {
  id: 'capture_test_001',
  version: '1.0' as const,
  timestamp: '2026-02-28T12:00:00.000Z',
  url: 'https://example.com/page',
  viewport: { width: 1440, height: 900 },
  element: {
    id: 'hero-button',
    tagName: 'button',
    styles: {
      'background-color': '#0075ca',
      'color': '#ffffff',
      'font-family': 'Inter, sans-serif',
      'font-size': '16px',
      'border-radius': '8px',
      'padding': '12px 24px',
      'display': 'flex',
      'opacity': '1',
    },
    pseudo: { before: {}, after: {} },
    children: [],
    boundingBox: { x: 100, y: 200, width: 150, height: 48 },
  },
};

describe('Extension → JSON → Plugin integration', () => {
  it('JSON generated by extension is parseable by plugin', () => {
    const json = JSON.stringify(validCapture);
    const parsed = parseJSON(json);
    expect(parsed.version).toBe('1.0');
    expect(parsed.element.tagName).toBe('button');
  });

  it('valid capture passes plugin validation', () => {
    expect(() => validateImportData(validCapture)).not.toThrow();
  });

  it('invalid capture (wrong version) fails plugin validation', () => {
    const invalid = { ...validCapture, version: '2.0' };
    expect(() => validateImportData(invalid)).toThrow();
  });

  it('incomplete capture fails plugin validation', () => {
    const incomplete = { version: '1.0', timestamp: '2026-02-28T12:00:00.000Z' };
    expect(() => validateImportData(incomplete)).toThrow();
  });

  it('JSON round-trip preserves element data', () => {
    const json = JSON.stringify(validCapture);
    const parsed = parseJSON(json);
    expect(parsed.element.styles['background-color']).toBe('#0075ca');
    expect(parsed.element.boundingBox.width).toBe(150);
  });
});
